language: python
matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
        - python: 3.6
          env: TOXENV=py36
install:
    - pip install sexpr==0.1.2
    - pip install tox==3.0.0
    - pip install coveralls==1.3.0
    - pip install coverage==4.5.1
    - pip install pytest
before_script:
    - coverage erase
script:
    - coverage run --source=booldog -m pytest tests/__init__.py; tox
after_success:
    - COVERALLS_REPO_TOKEN=Me4RKkNYVHz7P9yNFpAn8Pj7HUf9c1pi6 coveralls
